services:
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.helth.dev`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PORT=3000
      - WHOOP_CLIENT_ID=${WHOOP_CLIENT_ID}
      - WHOOP_CLIENT_SECRET=${WHOOP_CLIENT_SECRET}
      - WHOOP_REDIRECT_URL=${WHOOP_REDIRECT_URL}
      - FITBIT_VALIDATION_CODE=${FITBIT_VALIDATION_CODE}
      - FITBIT_CLIENT_ID=${FITBIT_CLIENT_ID}
      - FITBIT_CLIENT_SECRET=${FITBIT_CLIENT_SECRET}
      - FITBIT_REDIRECT_URL=${FITBIT_REDIRECT_URL}
  discord-client:
    container_name: discord-client
    build:
      context: ./discord-client/
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`discord.helth.dev`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3001
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
  frontend:
    container_name: helth-frontend
    build:
      context: ./fe-auth/
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`helth.dev`)"
      - "traefik.http.services.api.loadbalancer.server.port=3002"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3002
      - API_URL=${API_URL}
  postgres:
    container_name: postgres
    image: postgres:17.2
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    container_name: redis
    image: redis:7.4
    ports:
      - 6379:6379
    restart: always
