name: Deploy API
run-name: 'API: ${{github.actor}} deploying ${{github.ref}} to ${{github.event.inputs.environment}}' 
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                default: 'test'
                options:
                    - 'test'
                    - 'prod'
env:
    SERVICE_NAME: helth-service-api-${{ github.event.inputs.environment }}
    REGION: us-central1
defaults:
    run:
        working-directory: ./api
jobs:
    build-push-image:
        runs-on: ubuntu-latest
        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v4"
            -
                name: "Deploy to ${{ github.event.inputs.environment }}"
                run: |
                    if [ "${{ github.event.inputs.environment }}" = "test" ]; then
                        echo "Deploying to test"
                    elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
                        echo "Deploying to prod"
                    else
                        echo "Invalid environment"
                        exit 1
                    fi
            - 
                name: "Setup node"
                uses: "actions/setup-node@v4"
                with:
                    node-version: '22'
            -
                id: "auth"
                uses: "google-github-actions/auth@v1"
                with:
                    credentials_json: "${{secrets.SERVICE_ACCOUNT_KEY}}"
                    token_format: 'access_token'
            -
                id: "docker-auth"
                name: "Auth docker"
                uses: 'docker/login-action@v3'
                with:
                    username: 'oauth2accesstoken'
                    password: '${{steps.auth.outputs.access_token}}'
                    registry: 'us-docker.pkg.dev'
            - 
                name: "Build & deploy"
                run: npm run deploy
    create-cloud-run-revision:
        runs-on: ubuntu-latest
        needs: build-push-image
        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v4"
            -
                id: "auth"
                name: "Auth with gcloud"
                uses: "google-github-actions/auth@v1"
                with:
                    credentials_json: "${{secrets.SERVICE_ACCOUNT_KEY}}"
            -
                name: Deploy to Cloud Run
                id: deploy
                uses: google-github-actions/deploy-cloudrun@v2
                with:
                    image: us-docker.pkg.dev/helth-service-test/helth-ar/api:latest
                    service: ${{env.SERVICE_NAME}}
                    region: ${{env.REGION}}

